version: "3.9"

services:
  
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
              #schema-registry:
              #  url: "http://schema-registry:8085"
              #connect:
              #  - name: "connect"
              #    url: "http://connect:8083"

    ports:
      - 8080:8080
    links:
      - kafka-1
      - kafka-2
      - kafka-3
      #- schema-registry

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    volumes:
      - "kafka_1_data:/bitnami"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper

  kafka-2:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    volumes:
      - "kafka_2_data:/bitnami"
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper    

  kafka-3:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
    volumes:
      - "kafka_3_data:/bitnami"
    environment:
      - KAFKA_CFG_BROKER_ID=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper

  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile


volumes:
  zookeeper_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  kafka_3_data:
    driver: local
