version: "3.9"

services:
  
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-broker:9092"
              #schema-registry:
              #  url: "http://schema-registry:8085"
              #connect:
              #  - name: "connect"
              #    url: "http://connect:8083"
    ports:
      - 8080:8080
    networks:
      - scdf

networks:
  scdf:

